steps:
  # Pull the previous image so its layers can be reused as cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull us-central1-docker.pkg.dev/data8x-scratch/otter-images/otter-srv:latest || true'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from=us-central1-docker.pkg.dev/data8x-scratch/otter-images/otter-srv:latest'
      - '--build-arg'
      - 'OTTER_SERVICE_VERSION=$_TAG_NAME'
      - '-t'
      - 'us-central1-docker.pkg.dev/data8x-scratch/otter-images/otter-srv:$_TAG_NAME'
      - '-t'
      - 'us-central1-docker.pkg.dev/data8x-scratch/otter-images/otter-srv:latest'
      - '.'

  # push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/data8x-scratch/otter-images/otter-srv']

images:
  - 'us-central1-docker.pkg.dev/data8x-scratch/otter-images/otter-srv:$_TAG_NAME'
  - 'us-central1-docker.pkg.dev/data8x-scratch/otter-images/otter-srv:latest'
timeout: 1200s
substitutions:
  _TAG_NAME: ""
