# Default values for otter-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
updateStrategy: RollingUpdate
nameOverride: otter-srv
fullnameOverride: otter-pod
otter_srv:
    name: otter-srv
    repository: gcr.io/data8x-scratch/otter-srv
    pullPolicy: Always
    tag: latest
    resources:
        limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi
    ports:
        - name: http
          containerPort: 80
          protocol: TCP
    volumeMounts:
        - name: opt-volume
          mountPath: /opt
        - name: tmp-volume
          mountPath: /tmp
    env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        - name: DOCKER_CLI_EXPERIMENTAL
          value: enabled
dind_image:
    name: otter-dind
    repository: docker
    tag: 20-dind
    args:
        - --tls=false
    imagePullPolicy: Always
    securityContext:
        privileged: true
    resources:
        limits:
            cpu: 2500m
            ephemeral-storage: 1Gi
            memory: 8Gi
        requests:
            cpu: 2500m
            ephemeral-storage: 1Gi
            memory: 5Gi
    volumeMounts:
        - name: opt-volume
          mountPath: /opt
        - name: tmp-volume
          mountPath: /tmp
    env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
serviceAccount:
    create: true
    annotations:
        iam.gke.io/gcp-service-account: otter-sa@data8x-scratch.iam.gserviceaccount.com
    name: otter-k8-sa
storageClass:
    create: true
    name: otter-srv-storage-class
    accessModes: ReadWriteOnce
    storageRequest: 1Gi
    type: pd-standard
volume_claims:
    names:
        - otter-opt-volume-claim
        - otter-tmp-volume-claim
otter_env:
    name: otter-env
    parameters:
        verbose_logging: "True"
        gcp_project_id: data8x-scratch
        post_grade: "True"
        edx_url: courses.edx.org
        jh_api_token: ENC[AES256_GCM,data:gZ0QFhVRSoivWlnkDJ+6xLICWPzOiM5jgcAX+dYNKUE=,iv:GANSTv7ijYRkQF0+57T/I0wvWAPRleTNnHuBakPn730=,tag:Y3rCk8VC1j7Rf/0b/PLAQg==,type:str]
        jh_client_id: service-otter_grade
        jh_service_prefix: /services/otter_grade/
        jh_service_name: otter_grade
        test_user: 594aed203b01b16a7a025c2f3e037933
service:
    name: otter-lb
    enabled: true
    type: LoadBalancer
    port: 10101
    targetPort: 10101
autoscaling:
    apiVersion: autoscaling/v1
    enabled: true
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: otter-pod
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/data8x-scratch/locations/global/keyRings/data8x-sops/cryptoKeys/otter-service
          created_at: "2023-12-19T02:10:27Z"
          enc: CiQA+mtdj0kP/7lUCRvGkmahoorhUnFGwk446UiQvrzuSbee1cMSSQAeeyex8eKDwX7hQz1JbDPN1p+lT8sOgpVMzD6PGlo6MvfbPHz3zV7DzBAcO4NLpgHQ+cXzeIsJBvJ9sDvUvX1xII5NNiJkGsA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-19T02:10:28Z"
    mac: ENC[AES256_GCM,data:rsyGsw5lnefe2aBc+/8EJ4EXLXADaiSNU+uqXFRIlTBmtyiIehybciqm5lS1FfRKVifjLYksweu9GT6jGQheUdwuYzxFQ/sRCqNuAkJNfr9NKogofGB1Ri6XRgrozr6Z8OuM3gGksag+2qE2ujH/mobp3JPna4PlsV5yA6nkcXI=,iv:+J0cDTjYo6wCBfJMjAUrEHiV9jf82QqdfCUEyBRPFek=,tag:f5PP47lCqnB1u9yj2asqbg==,type:str]
    pgp: []
    encrypted_regex: jh_api_token
    version: 3.7.1
