branch: prod
service:
    load_balancer_ip: 35.224.71.117
otter_srv:
    envFrom:
        - configMapRef:
            name: otter-env-prod
otter_env:
    parameters:
        environment: otter-prod
        jh_api_url: https://edx.datahub.berkeley.edu/hub/api
        jh_base_url: https://edx.datahub.berkeley.edu
        jh_api_token: ENC[AES256_GCM,data:uOVqzsHqZDuX3YQZzcDAjDnTIvKRGfs0IzZ5x7l+r+s=,iv:N5SSHPTGBXRMnRJFnH2G6fXL6bc0+RV9bDilUmpyAsE=,tag:LQQ2+jvy1yCKSXLs+HtRQQ==,type:str]
        post_grade: "True"
volume_claims:
    create: false
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/data8x-scratch/locations/global/keyRings/data8x-sops/cryptoKeys/otter-service
          created_at: "2023-12-20T18:24:25Z"
          enc: CiQA+mtdj2jGUXbahzhvzklwPGEQABYGFV3wl3Q16cqTPm2InDESSQAeeyexjfVHVTxsWg6IDH5kYvHBYSPRcj6ywbhaL4P9yfSoNf58hm6vE5femJyg5X81ppI6FeFzs+/6Pgqi9IJpPHDsqzlWrIk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-20T18:24:25Z"
    mac: ENC[AES256_GCM,data:n0K2OXjciSS1tN83gYzYHXpS+6Qe3npUxdsZcwbDWZ4xbVLSaj7VCNYIYw4UxevYLOFth0I69uii8/PyHSD2K3AK3ZV6pJ6NshCLFNZHMa7VcygYwsVRJrj3PpGq+4YcwMwikXNIXZmQ17miNui1DFZUALWlH5RDi6qBazlIK3s=,iv:XYH1z1aJsH2/j2sifruJ5+IOeXyT1SRBODOz4z6AtYw=,tag:aQSxEpfYn8oAAmInoNu+0g==,type:str]
    pgp: []
    encrypted_regex: jh_api_token
    version: 3.7.1
