branch: staging
service:
    load_balancer_ip: 35.193.0.244
otter_srv:
    envFrom:
        - configMapRef:
            name: otter-env-staging
otter_env:
    parameters:
        environment: otter-staging
        jh_api_url: https://edx-staging.datahub.berkeley.edu/hub/api
        jh_base_url: https://edx-staging.datahub.berkeley.edu
        jh_api_token: ENC[AES256_GCM,data:mt/f7+Ay12yGCJH7lnOCNVMzgqAaIXjtmMKA18+ZnFw=,iv:3DeUDSU08rucNIkJPL3qVSSiWxYnmzC8i9Krfygksfc=,tag:QsQNFXprs32djgdMtNabSQ==,type:str]
        post_grade: "True"
volume_claims:
    create: true
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/data8x-scratch/locations/global/keyRings/data8x-sops/cryptoKeys/otter-service
          created_at: "2023-12-20T18:24:04Z"
          enc: CiQA+mtdj+BmYjIMEFX1sr7kshGLxs2lwRFzYaehmoPkPqpi15YSSQAeeyex8FEY5BjLoJyJOnuA/J34YKVbIZbal5jPUsgV++6KhvXXs7/NfnxztCrgMZyQVnCEDZI74X9Qxo0QAeiSt97MIKL2bpc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-20T18:24:05Z"
    mac: ENC[AES256_GCM,data:3883b+kMiS9WCqhUSCMy7gvawvNW46y8+NJuKs+FZEsinO/lfyM9O61Qkhu+LNk3ihYSutMblyIjgMKO30PW6HhukSJBZbCMHXatWw1n3+CnCyAyfOjsSjLU400GpNEcsgGbrdw0qZ/yk2n54OrFo09T9RWhjqf2PvkmnnX8kZo=,iv:HhCBJJXNaU/5+nPXs3S9qxz0FuCsMnXQUrWn9POKTOc=,tag:3ecujXQloGYC7CpCvRX/bw==,type:str]
    pgp: []
    encrypted_regex: jh_api_token
    version: 3.7.1
